Algoritmo "Questão 3"
// Fazer um programa que pergunte um
//valor em Dólares e apresente o equivalente em Reais.
//Considere U$1,00 = R$1,72
Var
// Seção de Declarações das variáveis 
 dol: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Informe um valor em Dólares")
 leia(dol)
 
 escreval(dol, " dólares correspondem à ", (dol * 1,72), " reais")

Fimalgoritmo